In [1]:
print("Hello numpy")

Hello numpy


In [2]:
pip install numpy pandas matplotlib scikit-learn openpyxl seaborn

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/28/75/3b679b41713bb60e2e8f6e2f87be72c971c9e718b1c17b8f8749240ddca8/numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.2 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 372.4 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 361.5 kB/s eta 0:00:00
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/df/92/a3fa053c74198f9f0224b2c04dc74f41d2e14e30329c082f7a657f9ca4c5/pandas-2.1.3-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/2e/51/c77a14869b7eb9d6fb440e811b754fc3950d6868c38ace57d0632b674415/matplotlib-3.8.2-cp312-cp312-win_amd64.whl


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

### NumPy

* Numerical Python - majorely works with array called ndarray
* ndarray - n dimensional array
* Stastical library comes with many statistical functions and packages
* Numpy is the fast processed library built with C compiler
* Every numpy array is alrady compiled with C so that it will take less time to execute
* Why numpy is developed where python already has list data structure?
* numpy array caluculation is done elementwise
* Default datatype in numpy is float
* it can store string, integer also

In [2]:
ls = [1,2,3,4,5,6,8]

In [3]:
ls

[1, 2, 3, 4, 5, 6, 8]

In [4]:
ls[4]

5

In [5]:
arr = np.array([1,2,3,4,5,6,7,8])

In [6]:
arr[4]

5

In [7]:
ls2 = [[1,2,3], [4,5,6], [7,8,9]]
ls2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2    # Matrix 3 X 3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2.ndim    # ndim is the number of dimension

2

In [10]:
ls*2

[1, 2, 3, 4, 5, 6, 8, 1, 2, 3, 4, 5, 6, 8]

In [11]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [12]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [13]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2.shape   # Shape shows number of rows and columns

(3, 3)

In [16]:
arr2.size    # Size returns number of element in array

9

In [17]:
arr3 = np.arange(5, 67, 8)
arr3

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [18]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
arr4 = np.arange(1, 65)

In [21]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [22]:
arr4.ndim

1

In [23]:
arr4.shape

(64,)

In [24]:
arr4.size

64

In [25]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [26]:
a = (10,)

In [27]:
type(a)

tuple

In [28]:
b = 4,7,2,6

In [29]:
type(b)

tuple

In [30]:
c = 45,

In [31]:
type(c)

tuple

In [32]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [33]:
arr4.reshape(2,32)   # Reshape used to change dimension of array, while doing it we cannot change size of an array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [34]:
arr4.reshape(4, 16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [35]:
arr4.reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [36]:
arr4.reshape(16, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60],
       [61, 62, 63, 64]])

In [37]:
arr4.reshape(32,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42],
       [43, 44],
       [45, 46],
       [47, 48],
       [49, 50],
       [51, 52],
       [53, 54],
       [55, 56],
       [57, 58],
       [59, 60],
       [61, 62],
       [63, 64]])

In [38]:
arr4.reshape(64,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])

In [39]:
arr4.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64]])